apiVersion: v1
kind: ConfigMap
metadata:
  name: front
  namespace: openloyalty
data:
  config.js: |-
          const config = {
              "apiUrl": "http://35.181.6.93/api",
              "dateFormat": "YYYY-MM-DD",
              "dateTimeFormat": "YYYY-MM-DD HH:mm",
              "perPage": 20,
              "debug": false,
              "modules": []
          };
          window.OpenLoyaltyConfig = {
              "apiUrl": "http://35.181.6.93/api",
              "dateFormat": "YYYY-MM-DD",
              "dateTimeFormat": "YYYY-MM-DD HH:mm",
              "perPage": 20,
              "debug": false,
              "modules": []
          };
