apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: elk
  name: elk
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: elk
    spec:
      containers:
      - name: openloyalty-elk
        resources: {}
      restartPolicy: Always
status: {}
