apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mail
  name: mail
spec:
  ports:
  - name: "8186"
    port: 8186
    targetPort: 8025
  selector:
    io.kompose.service: mail
status:
  loadBalancer: {}
