apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
    spec:
      containers:
      - name: openloyalty-frontend
        ports:
        - containerPort: 80
        - containerPort: 3001
        - containerPort: 3002
        - containerPort: 3003
        resources: {}
      restartPolicy: Always
status: {}
